name: ci
on: [push, pull_request]

jobs:
  nixpkgs-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA nixpkgs-fmt
      - run: |
          find . -name '*.nix' -print0 | while IFS= read -r -d '' file; do
            nixpkgs-fmt --check "$file"
          done
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA actionlint
      - run: actionlint
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA black
      - run: black --check .
  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-shell --run "mypy ."
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-shell --run "pytest"
